apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-oppslag-ytelser
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 99%
  azure:
    application:
      enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  kafka:
    pool: {{ kafka.pool }}
  secureLogs:
    enabled: true
  webproxy: true
